app/blog/routes.py
from flask import Blueprint, render_template, request, jsonify, flash, redirect, url_for
from flask_login import current_user, login_required
from app.models import db, User, Post, load_user
from .blogforms import PostForm

blog = Blueprint('blog', __name__, template_folder='blog_templates', url_prefix='/blog')

@blog.route('/<string:username>', methods=['GET', 'POST'])
def userProfile(username):
    user = User.query.filter_by(username=username).first()
    if user:
        posts = Post.query.filter_by(user_id=user.id).order_by(Post.timestamp.desc()).all()
    else:
        # replace with 404 redirect later
        return render_template('userprofile.html', user=None, posts=None)
    # if we get here, a user exists with this username
    form = PostForm()
    if request.method == 'POST' and current_user.is_authenticated:
        if current_user.id == user.id and form.validate_on_submit():
            # normal post stuff
            newpost = Post()
            newpost.body = form.new_post.data
            newpost.user_id = current_user.id
            db.session.add(newpost)
            db.session.commit()
            flash('New post created :)', 'success')
            return redirect(url_for('blog.userProfile', username=current_user.username))
        else:
            # someone tried to bypass the template, don't let them
            return jsonify({'Come on': 'you shouldnt be here'}), 403
    return render_template('userprofile.html', user=user, posts=posts, form=form)


# pretty common structure for a route for a button that does some interaction with database
# has its own route which does some stuff then redirects back to a route that renders a template
@blog.route('/delete/<int:pid>')
@login_required
def deletePost(pid):
    to_delete = Post.query.get(pid)
    if current_user.id == to_delete.user_id:
        db.session.delete(to_delete)
        db.session.commit()
        flash('Post deleted successfully.', 'info')
        return redirect(url_for('blog.userProfile', username=current_user.username))
    return jsonify({'Come on': 'you shouldnt be here'}), 403

@blog.route('/users')
def users():
    if current_user.is_authenticated:
        users = User.query.filter(User.id!=current_user.id).all()
    else:
        users = User.query.all()
    return render_template('findusers.html', users=users)

@blog.route('/newsfeed')
def newsfeed():
    if current_user.is_authenticated:
        # this will change to a different query when we have our follower system built
        posts = current_user.followed_posts()
        print(current_user.followed)
    else:
        # no one signed in? show all the posts
        posts = Post.query.order_by(Post.timestamp.desc()).all()   
    return render_template('newsfeed.html', posts=posts)

@blog.route('/follow/<string:uid>')
@login_required
def follow(uid):
    u = User.query.get(uid)
    current_user.follow(u)
    flash(f'Followed @{u.username}', 'info')
    return redirect(url_for('blog.userProfile', username=u.username))

@blog.route('/unfollow/<string:uid>')
@login_required
def unfollow(uid):
    u = User.query.get(uid)
    current_user.unfollow(u)
    flash(f'Unfollowed @{u.username}', 'warning')
    return redirect(url_for('blog.userProfile', username=u.username))

app/templates/components/layout.html
<!doctype html>
<html lang="en">

<head>
  <title>Foxes90 | Flask</title>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <!-- custom CSS -->
  <link rel="stylesheet" href="../../static/css/main.css">
  {% block css %}
  {% endblock css%}
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-info">
    <a class="navbar-brand" href="{{ url_for('home') }}">Foxes90</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <div class="navbar-nav">
        <a class="nav-link" href="{{ url_for('home') }}">Home</a>
        <a class="nav-link" href="{{ url_for('mancity') }}">Soccer News</a>
        <a class="nav-link" href="{{ url_for('gallery') }}">Gallery</a>
        <a class="nav-link" href="{{ url_for('f1drivers') }}">F1 Drivers</a>
        <a class="nav-link" href="{{ url_for('blog.newsfeed') }}">Newsfeed</a>
        <a class="nav-link" href="{{ url_for('blog.users') }}">Find Users</a>
      </div>
      <div class="navbar-nav ml-auto">
        {% if current_user.is_authenticated %}
        <a class="nav-link" href="{{ url_for('blog.userProfile', username=current_user.username)}}">{{ current_user.username }}</a>
        <a class="nav-link" href="{{ url_for('auth.signout') }}">Logout</a>
        {% else %}
        <a class="nav-link" href="{{ url_for('auth.signin') }}">Login</a>
        {% endif %}
      </div>
    </div>
  </nav>
  <div class="container-fluid mt-2">
    <div class="row justify-content-center">
      {% with messages = get_flashed_messages(with_categories=True) %}
      {% if messages %}
      {% for category, message in messages %}
      <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endfor %}
      {% endif %}
      {% endwith %}
    </div>
    {% block content %}
    {% endblock content %}
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
</body>

</html>